[build]
command = "npm run build"
publish = "public"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"

[headers.values]

"Cache-Control" = "public, max-age=31560000, immutable"

[functions]
external_node_modules = ["express"]
node_bundler = "esbuild"

[[redirects]]
force = true
from = "/*"
status = 200
to = "/.netlify/functions/server"