name: Node.js Unit Tests
on: 
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: develop
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Unit Tests
        env:
          SESSION_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TEST_FIREBASE_API_KEY: ${{ secrets.TEST_FIREBASE_API_KEY }}
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        run: npm run test